### ISSUE TITLE
Rules Command

### ISSUE THREAD

**Issue by GregTCLTK** [BigBotNetwork/Hadder#125]

**Comment by Schlauer-Hax** [comment]
Whats the bug?

**Comment by GregTCLTK** [comment]
https://github.com/BigBotNetwork/Hadder/blob/020f65fdf7b9a2b0277f74b20f2d0df91d8fb87e/src/main/java/com/bbn/hadder/listener/RulesListener.java#L32

**Comment by GregTCLTK** [comment]
Emoji Rethink check
