### ISSUE TITLE
[Suggestion] - Change reaction emoji for Rules

### ISSUE THREAD

**Issue by TheTopComp** [BigBotNetwork/Hadder#127]
I think it would be nice if you could change the emoji for Rules Reaction.
![obrázok](https://user-images.githubusercontent.com/55924795/69914188-78c7a100-1441-11ea-88fc-6c98c88989e6.png)

**Comment by GregTCLTK** [comment]
Deployed in #137

**Comment by GregTCLTK** [comment]
Full deploy with custom emotes. Not emojis!
