### ISSUE TITLE
[Suggestion] - Update Hadder´s picture

### ISSUE THREAD

**Issue by TheTopComp** [BigBotNetwork/Hadder#129]
Is possible to make Hadders Avatar more.. Modern?
I mean.. Something like this
![obrázok](https://user-images.githubusercontent.com/55924795/69914900-884ae800-1449-11ea-9356-7fb7b4892151.png)

**Comment by TheTopComp** [comment]
*I made that cloud btw xd

**Comment by GregTCLTK** [comment]
We would be very grateful if you could send us a list of possible designs. We would then choose one from it
