### ISSUE TITLE
Starboard

### ISSUE THREAD

**Issue by GregTCLTK** [BigBotNetwork/Hadder#178]

**Comment by Schlauer-Hax** [comment]
Where's the bug?

**Comment by GregTCLTK** [comment]
Where do you see a bug label?

**Comment by Schlauer-Hax** [comment]
Why reopened?

**Comment by GregTCLTK** [comment]
Can you translate "Under observation" to your language

**Comment by Schlauer-Hax** [comment]
no

**Comment by GregTCLTK** [comment]
Then you will probably not understand the reason :^)

**Comment by Schlauer-Hax** [comment]
I know what it is but its done.

**Comment by GregTCLTK** [comment]
Sometimes when we publish a new command we watch it for a while. If we do this the issue is in the "Under observation" column

**Comment by Schlauer-Hax** [comment]
i know

**Comment by GregTCLTK** [comment]
Now you know the reason :)
