### ISSUE TITLE
[Issue] h.rules - ⛔ No Permission ⛔

### ISSUE THREAD

**Issue by Big-Bot-Network** [BigBotNetwork/Hadder#245]
<strong>Feedback by TopComp#1288</strong><br>I can't use h.rules . It says that "I am not authorized to execute this command" even if I'm the owner of the discord group.
https://cdn.discordapp.com/attachments/448554629932908549/658849488789569546/Screenshot_20191224-025224.png

**Comment by TheTopComp** [comment]
*Okay it's fixed. The bot didn't have Admin Permission.
But still. I think he should say "I don't have permission to do that".
And not "you are not authorized to do that".
Thanks ♥️
