### ISSUE TITLE
[Translation] - Removed {1} messages.

### ISSUE THREAD

**Issue by TheTopComp** [BigBotNetwork/Hadder#265]
This is not a huge bug or something but.. If you remove 1 message, Hadder will say "I successfully deleted 1 messages!". Soo if it's possible to fix it somehow :D
Thanks ^-^

**Comment by GregTCLTK** [comment]
Can you explain that in more detail?

**Comment by TheTopComp** [comment]
If you remove ONE message, the bot will still say "Removed ONE messages". And "messages" is still in plular. Soo if its possible to fix that somehow xD

**Comment by GregTCLTK** [comment]
Oh yeah. We'll fix this

**Comment by GregTCLTK** [comment]
Fixed and deployed in #266
